### ISSUE TITLE
PendingUpdate type isn't exported

### ISSUE THREAD

**Issue by sgehrman** [meilisearch/meilisearch-dart#107]
let me know if that was intentional.

**Comment by brunoocasali** [comment]
Hi @sgehrman, could you give me more information about what you're trying to accomplish?

**Comment by brunoocasali** [comment]
@sgehrman we replaced the `PendingUpdate` to `TaskInfo` in the [release v0.5.0](https://github.com/meilisearch/meilisearch-dart/releases/tag/v0.5.0). 

I'll close this issue, if you have any follow-up questions, do not hesitate! 

Thanks for using Meilisearch ❤️
