### ISSUE TITLE
code: invalid_api_key on method getDocuments(limit: x) - Version 0.5.3

### ISSUE THREAD

**Issue by sauterle** [meilisearch/meilisearch-dart#168]
**Description**
The method  `getDocuments(limit: x)`  doesn't work with meilisearch 0.27.1
However  `search("", limit: x) ` as workaround works fine

**Expected behavior**
Get documents without invalid_api_key error

**Current behavior**
MeiliSearchApiError - message: The provided API key is invalid. - code: invalid_api_key - type: auth - link: https://docs.meilisearch.com/errors#invalid_api_key

**Environment (please complete the following information):**
- Meilisearch version: [0.27.1]
- meilisearch-dart version: [0.5.3]

**Comment by brunoocasali** [comment]
Hi @sauterle thanks for your issue!

Can you provide me with more details about your call? I would like to know how are you setting up the client that makes the calls because this error occurs usually when you have a misconfigured client.
You can read more here!

**Comment by brunoocasali** [comment]
@sauterle, I'll close this issue since you didn't answer back :). Feel free to reopen if you want to!
