### ISSUE TITLE
Code block in README is not closed properly

### ISSUE THREAD

**Issue by ShakyaCsun** [meilisearch/meilisearch-dart#177]
Example json response of `Custom Search With Filters` is not closed properly (missing ```) in README.md, which means rest of the README is incorrectly formatted as part of code block as shown in picture.

![image](https://user-images.githubusercontent.com/38353746/174258294-c3d07188-d63d-4318-bdd8-f08e0598486d.png)

**Comment by brunoocasali** [comment]
This issue was fixed!
