### ISSUE TITLE
Add property indexUid in `Task` class

### ISSUE THREAD

**Issue by huongtran84** [meilisearch/meilisearch-dart#202]
can you add indexUid property to Task class?. I try to use post man and get Task it return Task and have a property indexUid I want use it but in meilisearch-dart not included the property.

**Comment by brunoocasali** [comment]
Hello @huongtran84 can you tell me which Meilisearch server version are you using?

**Comment by huongtran84** [comment]
meilisearch 0.28.0

**Comment by brunoocasali** [comment]
Indeed there is no `indexUid` in the `Task` class.

The idea is to add a new property in the class and also in the factory. Be careful because this property is nullable.

Feel free to submit a PR to fix this issue @huongtran84 (or anybody else)🥇
