### ISSUE TITLE
Migrate to dio: 5.0.0

### ISSUE THREAD

**Issue by ahmednfwela** [meilisearch/meilisearch-dart#248]
Dio has recently changed ownership and dio v5 was released containing multiple enhancements and breaking changes
https://pub.dev/packages/dio

migration guide: https://github.com/cfug/dio/blob/main/dio/migration_guide.md#500

**Comment by brunoocasali** [comment]
Hi @ahmednfwela, thanks for your issue!

Indeed I received the bump PR from dependabot here https://github.com/meilisearch/meilisearch-dart/pull/243
But unfortunately I don't have enough time to work on this issue. I can assist you with code reviews if you want to take a shot in any case.
