### ISSUE TITLE
Add a section in the README about `withCustomDio`

### ISSUE THREAD

**Issue by brunoocasali** [meilisearch/meilisearch-dart#270]
After the https://github.com/meilisearch/meilisearch-dart/pull/266 implementation, it is now possible to use a custom implementation of the HTTP library in this package.

This issue aims to create a small section in the README explaining how to use this feature. Check the test file `test/custom_dio_test.dart` for more information.

**Comment by ahmednfwela** [comment]
do we need to update the code samples as well ?
