### ISSUE TITLE
[Discussion] using a modelling library

### ISSUE THREAD

**Issue by ahmednfwela** [meilisearch/meilisearch-dart#276]
**Description**
the current library behavior relies on generating models manually (including serialization, deserialization, copyWith, etc...)
this is [very](https://github.com/meilisearch/meilisearch-dart/pull/250) [error prone](https://github.com/meilisearch/meilisearch-dart/pull/274)

**Alternatives**
we can use build_runner to automatically generate serialization/deserialization bindings, similar to c# using reflection in runtime, instead this being at compile time.

here are some libraries for this:

- https://pub.dev/packages/json_serializable (very basic serialization only)
- https://pub.dev/packages/freezed (advanced, on top of json_serializable, adds copyWith, and equality)
- https://pub.dev/packages/dart_mappable (advanced, adds support for polymorphism, can be used on top of freezed or without)

we can even take it a step further and generate the http bindings via something like

- https://pub.dev/packages/openapi_freezed_dio_builder
- https://openapi-generator.tech/

**Comment by brunoocasali** [comment]
Hi @ahmednfwela 

Indeed, if we can automate some checking, it will be amazing.

But I would like to understand the possible pros and cons of adopting such a solution, especially in terms of maintenance and userland breaking changes.
Also, can we implement something like this in small steps, (incrementally) instead of creating a big-bang PR?

**Comment by ahmednfwela** [comment]
all the heavy lifting is done at generation time (before compile time) and at runtime everything is practically the same.

I will create some test PRs to see the best solution

**Comment by brunoocasali** [comment]
Do you think this subject is still relevant @ahmednfwela?

**Comment by ahmednfwela** [comment]
yes I am testing out this package https://pub.dev/packages/dart_json_mapper which seems like the best candidate for now

**Comment by ahmednfwela** [comment]
Closing this issue now, since we started using [json_serializable](https://pub.dev/packages/json_serializable) in the latest version
