### ISSUE TITLE
Add `copyWith` to `SearchQuery`

### ISSUE THREAD

**Issue by ahmednfwela** [meilisearch/meilisearch-dart#305]
going to need this for the flutter ui kit

**Comment by brunoocasali** [comment]
Can you give me more info about this method? I also asked that in the PR review so you can answer only here if you want!

**Comment by ahmednfwela** [comment]
since `SearchQuery` is immutable, we need a way to change certain values in it, which is why the `copyWith` is introduced.

why this is needed tho can be seen here

https://github.com/meilisearch/meilisearch-flutter/blob/ab97f0eee4fda9512491dae165b28bebbc77ad61/lib/src/widgets/query_builders/offset_based.dart#L99-L122

where we manipulate the input query to automatically progress the search results based on scroll
