### ISSUE TITLE
Update lints package to the latest version

### ISSUE THREAD

**Issue by brunoocasali** [meilisearch/meilisearch-dart#312]
- Force the constraint to get the latest package.
- Fix all the deprecations the new version triggers.

**Comment by ahmednfwela** [comment]
currently the constraint `lints: ">=1.0.1 <3.0.0"` will resolve to v2.1.0 just fine

**Comment by brunoocasali** [comment]
Shame on me. I forgot to publish the description of the issue! When I mean update, the idea is to fix all the deprecations introduced in the last version. I assume we have some because I tried in the past, and we had some...

**Comment by ahmednfwela** [comment]
oh I understand now, luckily the latest version has no conflicts with the package
