### ISSUE TITLE
Migration to null-safety

### ISSUE THREAD

**Issue by TheMisir** [meilisearch/meilisearch-dart#37]
Starting from Flutter 2.0 and Dart SDK 1.12.0, dart language now supports sound null safety which requires explicitly defining null values.

**Comment by TheMisir** [comment]
hey @curquiza , I've migrated the library to null safety on nnbd branch. I think we might release this version as a pre-release (1.0.0-nullsafety.0) for now. (I also increased minor version because nnbd migration is considered as breaking change).

**Comment by curquiza** [comment]
Hello @TheMisir! This package will not release a `1.0.0` version until we are sure we are stable, and most of all, until MeiliSearch is stable (release a `1.0.0`). This repository is even still considered as not ready for production at the moment. So no need to do a `1.0.0-nullsafety.0` tag. We can release the `0.2.0` version containing this nullsafety change.
Why would we need a pre-release for this?

**Comment by TheMisir** [comment]
I agree. Let's publish as v0.2.0.

**Comment by curquiza** [comment]
I think you can re-open https://github.com/meilisearch/meilisearch-dart/pull/42 right? 😁
