### ISSUE TITLE
Pana CI is failing

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-dart#377]
Pana CI is currently failing, we cannot merge anything

Asking for help @ahmednfwela because I don't know how to make this CI happy 😊 

I absolutely need to merge PRs and make a release on March 11th, so I will have to temporary remove it if it's still failing on March 11th 😢 

https://github.com/meilisearch/meilisearch-dart/actions/runs/7932951235/job/21660592699

<img width="1114" alt="Capture d’écran 2024-02-16 à 16 53 28" src="https://github.com/meilisearch/meilisearch-dart/assets/20380692/738ebe49-631b-467f-ba65-25a32061c5a3">

**Comment by ahmednfwela** [comment]
looks like pana can't find flutter for some reason
