### ISSUE TITLE
Impossible to deploy on Pub.dev

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-dart#382]
https://github.com/meilisearch/meilisearch-dart/actions/runs/8233664200/job/22513734761

Currently getting this kind of issues:

<img width="1086" alt="Capture d’écran 2024-03-11 à 14 58 36" src="https://github.com/meilisearch/meilisearch-dart/assets/20380692/f8be3cad-cf6e-4c9f-ab6c-b0c2e30678a2">

@ahmednfwela if you are around, do you know when it could come from? 😊

**Comment by ahmednfwela** [comment]
yes, seems to be an easy fix
