### ISSUE TITLE
Update Dio to ^4.0.0

### ISSUE THREAD

**Issue by Jethro87** [meilisearch/meilisearch-dart#39]
Dio ^3.0.0 is causing lots of dependency issues in my project, as other packages depend on http, which Dio also depends on, and these dependency clashes cannot be resolved. Dio 4.0.0 is stable and null-safe.

I forked this package and have been using it without issue after bumping Dio to ^4.0.0. I'm having a lot of trouble getting docker set up and working on my machine, though, so I haven't been able to run tests and submit a PR.

Can you bump Dio to ^4.0.0? Thanks.

**Comment by curquiza** [comment]
Hello @Jethro87!
Thanks for your feedback. Even if you didn't succeed to test locally your changes, you can submit your PR: the tests will run and we will be able to check together if there are any changes to apply before merging :) It would be awesome to have you on the contributor list 🙂

**Comment by Jethro87** [comment]
Thanks, @curquiza! PR here #41.
