### ISSUE TITLE
Implement `getAllUpdateStatus` and `getUpdateStatus` methods

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-dart#50]
- [ ] Implement `index.getAllUpdateStatus()` and `index.getUpdateStatus()` methods based on these routes: https://docs.meilisearch.com/reference/api/updates.html
- [ ] Add tests

We are really open to contributions! Feel free to ask any questions if anything is not clear 🙂

**Comment by sanders41** [comment]
This one it looks like `getUpdateStatus()` is already implemented [here](https://github.com/meilisearch/meilisearch-dart/blob/2b6bcb9b08e7b8af6fb48e900846188679cf0b8f/lib/src/pending_update_impl.dart#L19), but with the name `getStatus()`. I think only the `getAllUpdateStatus()` still needs implementing, or am I missing something? If this is correct should `getAllUpdateStatus()` instead be named `getAllStatus()` to match the other?

**Comment by curquiza** [comment]
Good point! Thanks :)
So, 
- `getAllUpdateStatus` should be implemented and tested
- `getStatus` should be renamed into `getUpdateStatus()`, should be accessible from `Index` and should be tested.
