### ISSUE TITLE
Test Suite Failure

### ISSUE THREAD

**Issue by sanders41** [meilisearch/meilisearch-dart#57]
I was looking at adding some of the methods listed in the issues, and after cloning I ran the test suite to make sure everything was good before making any changes. In doing this I am getting either test failures or the test suite freezes and never finishes.

One weird thing is when it fails I get different results. For example one time I got `+16 -23: Some tests failed.` and another time I got `+18 -21: Some tests failed. `. Nothing changed in the code between test runs and I stopped and restarted the MeiliSearch docker container to make sure there was nothing left from the previous run.

I have dart installed through Flutter and the output of `flutter doctor -v` is

```
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.4 20F71 darwin-x64, locale en-US)
    • Flutter version 2.2.2 at /Users/paul/development/flutter
    • Framework revision d79295af24 (13 days ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/paul/Library/Android/sdk
    • Platform android-30, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[!] Connected device
    ! No devices available
```

**Comment by curquiza** [comment]
Hello @sanders41! I got the same, and it works on the GH Action runners... We think it comes from MeiliSearch, not the Dart SDK. I will test with the new version of the search engine.

**Comment by sanders41** [comment]
Very interesting that it works in CI, but not locally. As a trouble shooting step I tried running the tests locally on Linux since GH Actions is using Linux, and got the same failures.

Out of curiosity I added the `getKeys` method and if I only run the test I added for that it passes. Since CI is working without issue and the new test passes I could do a PR, but I'm not sure if it would be better to solve this testing issue first. I'll do whatever you think would be the better option.

**Comment by sanders41** [comment]
I figured out the problem. There are 2 issues, one is easy to fix and the other will take some discussion to find the best solution.

1. This issue reminded me of the [multi-threading issue](https://github.com/meilisearch/meilisearch-rust/issues/109) in the Rust client tests so I looked and the Dart tests defaults to 4 threads. This explains why GH Actions is not having an issue because I believe it only has 1 CPU core available. This one is the easy fix. Running the tests with `pub run test --concurrency=1` tells it to only use 1 thread and this solves the biggest issue.
2. The second issue is with the bad route health tests. Specifically it is the [Health Fail group](https://github.com/meilisearch/meilisearch-dart/blob/090d9df325ba4f1c2b497fd715c2855971adfa0c/test/health_test.dart#L19-L30) in `health_tests.dart` with the issue. What is happening here is `Dio` is not timing out, but Dart tests time out after 30 seconds so the tests are failing because they timeout, not because `expect` fails. The default timeout of the Dart tests can be overriden, but I bumped the timeout all the way up to 1 minute and it didn't solve the issue (and wouldn't be ideal anyways because there would be a long wait for the tests). The solution here is to specify a `connectionTimeout` duration for `Dio`. The discussion comes in because I can think of a few different ways to do this. One way would be for a timeout to be hard coded into Dio.

```dart
class HttpRequestImpl implements HttpRequest {
  HttpRequestImpl(this.serverUrl, this.apiKey)
      : dio = Dio(BaseOptions(
          baseUrl: serverUrl,
          headers: <String, dynamic>{
            if (apiKey != null) 'X-Meili-API-Key': apiKey,
          },
          responseType: ResponseType.json,
          connectTimeout: 5000,  // 5 seconds but could be anything
        ));
  ...
```

Another option would be would be to pass a value in along with the url and api key. This is what we did in Python so you can look there as a reference.

```dart
class MeiliSearchClientImpl implements MeiliSearchClient {
  MeiliSearchClientImpl(this.serverUrl, [this.apiKey], this.connectionTimeout)
      : http = HttpRequestImpl(serverUrl, apiKey, connectionTimeout);

  ...
```

The third option I can think of is to add the mockito package to the dev dependencies and mock the `HttpRequestImpl` for these tests.

**Comment by curquiza** [comment]
Thanks for the investifation @sanders41! 😁

> This issue reminded me of the multi-threading issue in the Rust client tests so I looked and the Dart tests defaults to 4 threads. This explains why GH Actions is not having an issue because I believe it only has 1 CPU core available. This one is the easy fix. Running the tests with pub run test --concurrency=1 tells it to only use 1 thread and this solves the biggest issue.

Indeed!! I will update the CONTRIBUTING.md! :)

However I don't have any test failure anymore after the `--concurrency=1`...

**Comment by sanders41** [comment]
The health checks passed for you after setting `--concurrency=1`? I tested on both my Mac  and Linux computers and both failed on those two test, but passed everything else after setting the concurrency.

**Comment by curquiza** [comment]
I don't have any issue on my mac with the `--concurrency=1` 😅

**Comment by sanders41** [comment]
😕. I tried pulling upstream, but no changes so that isn't it. I have tried running the test with both `flutter pub run test --concurrency=1` and `flutter test --concurrency=1` and both always fail on those two tests. Maybe you are running them differently I'm running it wrong?

**Comment by curquiza** [comment]
Same result for 
- `flutter pub run test --concurrency=1`
- `flutter test --concurrency=1`
-  `pub run test --concurrency=1`

-> all tests pass. Really weird.

```
> pub --version
Pub 2.13.1
```

```
> flutter --version
Flutter 2.2.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d79295af24 (3 weeks ago) • 2021-06-11 08:56:01 -0700
Engine • revision 91c9fc8fe0
Tools • Dart 2.13.3
```

And I run

```
docker run -p 7700:7700 getmeili/meilisearch:v0.20.0 ./meilisearch --master-key=masterKey
```

**Comment by sanders41** [comment]
My flutter version and docker run are both the exact same. It looks like you also have a separate install of dart without flutter which I don't have. According to the dart docs using dart with and without flutter are the exact same, but I'll try installing dart on it's own in a bit just to see if it makes a difference.

**Comment by sanders41** [comment]
I have found that the only tests that use the [setupClientWrongUrl](https://github.com/meilisearch/meilisearch-dart/blob/e155dd6a61c1d58583f2e8519e7efbb755191c58/test/utils/client.dart#L49-L57) client are these health tests that are failing for me. The url set for this client is `http://wrongurl:1234`. I noticed that there are other testing using `http://wrongurl` without the port and those pass so I tried removing the port in `setupClientWrongUrl` and the tests pass if I do that.

My theory is it has something to do with the invalid url (no domain) with the port, but what I can't explain is why it passes for you and not me.

**Comment by curquiza** [comment]
If there is an issue on your side it might worth to fix it.
I think adding a connectionTimout (and optional) parameter as in the Python SDK might be a good solution since it brings a new feature at the same time

(FYI, I'm on holiday tomorrow for a month so I will not be present during this time 😇)

**Comment by sanders41** [comment]
Sounds good, I'll work on it.

I'm jealous of the European summer holidays, enjoy!
