### ISSUE TITLE
Method to get all the indexes should return a list of instance

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-dart#93]
Currently, the `geAllIndexes` method returns a raw list of object, but not a list of `Index` instance. This is the only index-related method that does not return an `Index` instance.

An instance is more convenient to manipulate than a raw object. See this [example](https://github.com/meilisearch/meilisearch-python/issues/258#issuecomment-835866135).

TODO

- [ ] Change the return of the current `geAllIndexes`: make it return a list of `Index` instances
- [ ] Provide `geAllRawIndexes`: a method that returns the list of object of indexes, so the response of the MeiliSearch server.
- [ ] Add tests

⚠️ No code duplication: use get_all_raw_indexes in get_all_indexes.

Related to https://github.com/meilisearch/integration-guides/issues/122

Sorry if this is already partially/completely implemented, feel free to let me know about the state of this issue.
Also, this issue is generated, and `getAllIndexes` might be named differently in this package

**Comment by brunoocasali** [comment]
I think this issue is not valid anymore since we have already returned a list of instances. 

`Future<Result<MeiliSearchIndex>> getIndexes({IndexesQuery? params})`
