### ISSUE TITLE
Add a method to delete the index only if it already exists

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-dart#94]
Trying to delete an index that does not exist on the MeiliSearch server will throw an error. To delete it without any error no matter what if it exists or not, we need a new method.

- [ ] Add a method `deleteIndexIfExists`: it deletes the index but does not throw any error if the index does not exist.
- [ ] Add tests

Example: https://github.com/meilisearch/meilisearch-python/pull/268/files

⚠️ This issue is generated, and `deleteIndexIfExists` might be named differently in this package. Keep the already existing way of naming in this package to stay idiomatic with the language and the repository.

Related to https://github.com/meilisearch/integration-guides/issues/107

Sorry if this is already partially/completely implemented, feel free to let me know about the state of this issue.

**Comment by MohsinNajmuddin** [comment]
@curquiza what is the state of the issue? Is it related to JavaScript?

**Comment by curquiza** [comment]
Hello @MohsinNajmuddin, no it's not related to javascript

The state of this issue is still ready to be implemented :)

**Comment by curquiza** [comment]
What do you mean with "related to the python"? I'm not sure to get your point

**Comment by curquiza** [comment]
According to https://github.com/meilisearch/integration-guides/issues/157#issuecomment-998826170, we decided to remove this method from the SDKs. I'm closing this issue
